projects:
  systems:
    description: This is for systems applications (e.g. Prometheus Operator)
    whitelistedGitRepos:
    - 'https://github.com/pliu/k8splayground.git'
    whitelistedNamespaces:
    - default
    - kube-system
    whitelistedClusterResources:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: policy
      kind: PodSecurityPolicy
    applications:
      node-problem-detector:
        source:
          repoURL: https://github.com/pliu/k8splayground.git
          targetRevision: master
          path: apps/node-problem-detector
        namespace: kube-system
      prometheus-operator:
        source:
          repoURL: https://github.com/pliu/k8splayground.git
          targetRevision: master
          path: apps/prometheus-operator
        namespace: default
        ignoreDifferences:
        - group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          jsonPointers:
          - /status
      nginx-ingress:
        source:
          repoURL: https://github.com/pliu/k8splayground.git
          targetRevision: master
          path: apps/nginx-ingress
        namespace: kube-system
      logging:
        source:
          repoURL: https://github.com/pliu/k8splayground.git
          targetRevision: master
          path: apps/logging
        namespace: kube-system

  apps:
    description: This is for user applications (e.g. mock server)
    whitelistedGitRepos:
    - 'https://github.com/pliu/k8splayground.git'
    whitelistedNamespaces:
    - default
    - distributor
    applications:
      mock-server:
        source:
          repoURL: https://github.com/pliu/k8splayground.git
          targetRevision: master
          path: apps/mock-server
        namespace: default
      airflow:
        source:
          repoURL: https://github.com/pliu/k8splayground.git
          targetRevision: master
          path: apps/airflow
        namespace: default
      distributor:
        source:
          repoURL: https://github.com/pliu/k8splayground.git
          targetRevision: master
          path: apps/distributor
        namespace: distributor
