projects:
  systems:
    description: This is for systems applications (e.g. Prometheus Operator)
    whitelistedGitRepos:
    - '*'
    whitelistedNamespaces:
    - default
    - kube-system
    whitelistedClusterResources:
    - group: '*'
      kind: ClusterRole
    - group: '*'
      kind: ClusterRoleBinding
    - group: '*'
      kind: CustomResourceDefinition
    - group: '*'
      kind: ValidatingWebhookConfiguration
    - group: '*'
      kind: MutatingWebhookConfiguration
    - group: '*'
      kind: PodSecurityPolicy
    applications:
      node-problem-detector:
        source:
          repoURL: https://github.com/pliu/k8splayground.git
          targetRevision: HEAD
          path: apps/node-problem-detector
          helm:
            releaseName: node-problem-detector
        namespace: default
      prometheus-operator:
        source:
          repoURL: https://github.com/pliu/k8splayground.git
          targetRevision: HEAD
          path: apps/prometheus-operator
          helm:
            releaseName: prometheus-operator
        namespace: default
        ignoreDifferences:
        - group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          jsonPointers:
          - /status
      nginx-ingress:
        source:
          repoURL: https://github.com/pliu/k8splayground.git
          targetRevision: HEAD
          path: apps/nginx-ingress
          helm:
            releaseName: nginx-ingress
        namespace: default

  apps:
    description: This is for user applications (e.g. mock server)
    whitelistedGitRepos:
    - '*'
    whitelistedNamespaces:
    - default
    applications:
      mock-server:
        source:
          repoURL: https://github.com/pliu/k8splayground.git
          targetRevision: HEAD
          path: apps/mock-server
          helm:
            releaseName: mock-server
        namespace: default
