apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      tolerations:
      - key: playground_test
        operator: Exists
        effect: NoSchedule
      nodeSelector:
        mock-server: "true"
      containers:
      - image: mock-server:0.0.1
        name: {{ .Release.Name }}
