airflow:
  airflow:
    extraPipPackages:
    - airflow-exporter
    config:
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"

  serviceMonitor:
    enabled: true
    path: /airflow/admin/metrics

  flower:
    urlPrefix: /airflow/flower

  web:
    baseUrl: http://localhost/airflow
    livenessProbe:
      initialDelaySeconds: 40
      failureThreshold: 3
    readinessProbe:
      initialDelaySeconds: 40
      failureThreshold: 3

  ingress:
    enabled: true
    web:
      path: /airflow
    flower:
      path: /airflow/flower(/|$)(.*)
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2

  dags:
    git:
      url: https://github.com/pliu/k8splayground.git
      ref: master

      gitSync:
        enabled: true
        refreshTime: 60

  workers:
    tolerations:
    - key: playground_test
      operator: Exists
      effect: NoSchedule
    replicas: 2
    celery:
      instances: 4
