airflow:
  airflow:
    extraPipPackages:
    - airflow-exporter
    config:
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
      AIRFLOW__WEBSERVER__BASE_URL: "http://localhost/airflow"
      AIRFLOW__CELERY__FLOWER_URL_PREFIX: "/airflow/flower"
    users:
    - username: admin
      password: password
      role: Admin
      email: admin@example.com
      firstName: admin
      lastName: admin

  serviceMonitor:
    enabled: true
    path: /airflow/admin/metrics

  web:
    livenessProbe:
      initialDelaySeconds: 40
      failureThreshold: 3
    readinessProbe:
      initialDelaySeconds: 40
      failureThreshold: 3

  ingress:
    enabled: true
    web:
      path: /airflow
    flower:
      path: /airflow/flower

  dags:
    gitSync:
      enabled: true
      repo: https://github.com/pliu/k8splayground.git
      branch: master
      syncWait: 60

  workers:
    tolerations:
    - key: playground_test
      operator: Exists
      effect: NoSchedule
    replicas: 2
