apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels: {{ .Values.labels | toYaml | nindent 6 }}
  template:
    metadata:
      labels: {{ .Values.labels | toYaml | nindent 8 }}
    spec:
      tolerations:
      - key: playground_test
        operator: Exists
        effect: NoSchedule
      containers:
      - name: node-problem-detector
        command:
        - /node-problem-detector
        - --logtostderr
        - --config.custom-plugin-monitor=/config/custom-plugin.json
        - --prometheus-address=0.0.0.0
        - --prometheus-port={{ .Values.metrics_port }}
        image: k8s.gcr.io/node-problem-detector:v0.8.1
        resources:
          limits:
            cpu: 10m
            memory: 80Mi
          requests:
            cpu: 10m
            memory: 80Mi
        securityContext:
          privileged: true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: log
          mountPath: /var/log
          readOnly: true
        - name: kmsg
          mountPath: /dev/kmsg
          readOnly: true
        # Make sure node problem detector is in the same timezone
        # with the host.
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: config
          mountPath: /config
          readOnly: true
        - name: usr
          mountPath: /usr
          readOnly: true
      volumes:
      - name: log
        # Config `log` to your system log directory
        hostPath:
          path: /var/log/
      - name: kmsg
        hostPath:
          path: /dev/kmsg
      - name: usr
        hostPath:
          path: /usr
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: config
        configMap:
          name: {{ .Release.Name }}
          defaultMode: 0555
          items:
          - key: custom-plugin.json
            path: custom-plugin.json
          - key: custom-check.sh
            path: custom-check.sh
          - key: custom-check2.sh
            path: custom-check2.sh
