kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
  labels: {{ .Values.labels | toYaml | nindent 4 }}
spec:
  selector: {{ .Values.labels | toYaml | nindent 4 }}
  ports:
  - name: prom-metrics
    port: {{ .Values.metrics_port }}
