prometheus-operator:
  defaultRules:
    create: false

  nodeExporter:
    serviceMonitor:
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: nodeName
          action: replace
