prometheus-operator:
  defaultRules:
    create: false

  kubeEtcd:
    service:
      targetPort: 2381

  nodeExporter:
    serviceMonitor:
      relabelings:
      - sourceLabels: 
        - __meta_kubernetes_pod_node_name
        targetLabel: nodeName
        action: replace

  grafana:
    adminPassword: password

    grafana.ini:
      log:
        mode: console
      paths:
        data: /var/lib/grafana/data
        logs: /var/log/grafana
        plugins: /var/lib/grafana/plugins
        provisioning: /etc/grafana/provisioning
      server:
        root_url: http://localhost/grafana

    defaultDashboardsEnabled: false

    service:
      port: 9090

  prometheus:
    additionalServiceMonitors:
    - name: node-problem-detector
      namespaceSelector:
        matchNames:
        - kube-system
      selector:
        matchLabels:
          app: node-problem-detector
      endpoints:
      - port: prom-metrics
        relabelings:
        - sourceLabels:
          - __meta_kubernetes_pod_node_name
          targetLabel: nodeName
          action: replace
        metricRelabelings:
        - regex: __name__|endpoint|nodeName|reason|service
          action: labelkeep
          
    - name: nginx-ingress
      namespaceSelector:
        matchNames:
        - default
      selector:
        matchLabels:
          app: nginx-ingress
      endpoints:
      - port: metrics

    prometheusSpec:
      externalUrl: prometheus
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      logLevel: debug
      externalLabels:
        cluster: test

    service:
      port: 9090

  alertmanager:
    alertmanagerSpec:
      externalUrl: http://localhost/alertmanager
      configSecret: alertmanager-config
      logLevel: debug
    service:
      port: 9090

alertmanagerConfig:
  url: http://mock-server.default.svc.cluster.local/
