prometheus-operator:
  global:
    rbac:
      pspEnabled: false

  defaultRules:
    create: false

  kubeEtcd:
    service:
      targetPort: 2381

  nodeExporter:
    serviceMonitor:
      relabelings:
      - sourceLabels:
        - __meta_kubernetes_pod_node_name
        targetLabel: nodeName
        action: replace

  grafana:
    rbac:
      pspEnabled: false
    adminPassword: password
    grafana.ini:
      log:
        mode: console
      paths:
        data: /var/lib/grafana/data
        logs: /var/log/grafana
        plugins: /var/lib/grafana/plugins
        provisioning: /etc/grafana/provisioning
      server:
        root_url: http://localhost/grafana
    defaultDashboardsEnabled: false
    service:
      port: 9090

  prometheus:
    prometheusSpec:
      externalUrl: prometheus
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      logLevel: debug
      externalLabels:
        cluster: test
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: standard
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 30Gi
    service:
      port: 9090

  alertmanager:
    alertmanagerSpec:
      externalUrl: http://localhost/alertmanager
      configSecret: alertmanager-config
      logLevel: debug
    service:
      port: 9090

  prometheusOperator:
    createCustomResource: false
    admissionWebhooks:
      enabled: false
    tlsProxy:
      enabled: false

  kube-state-metrics:
    podSecurityPolicy:
      enabled: false

  prometheus-node-exporter:
    rbac:
      create: false

alertmanagerConfig:
  url: http://mock-server.default.svc.cluster.local/
