groups:
- name: toy_alerts
  rules:
  - alert: ProblemCounterHigh
    annotations:
      message: 'Problem counter high on {{ $labels.nodeName }}: {{ $value }}'
      test: 'This is an external label: {{ $externalLabels.cluster }}'
    expr: problem_counter{reason="TempProblem2"} > 5
    for: 1m
    labels:
      severity: critical
