groups:
- name: watchdog
  rules:
  - alert: Watchdog
    annotations:
      message: This is a DeadMansSwitch meant to ensure that the entire Alerting pipeline is functional
    expr: vector(1)
    labels:
      severity: critical