elasticsearch:
  antiAffinity: soft
  tolerations:
  - key: playground_test
    operator: Exists
    effect: NoSchedule
  esConfig:
    elasticsearch.yml: |
      xpack:
        monitoring:
          collection:
            enabled: true

kibana:
  httpPort: 5601
  kibanaConfig:
    kibana.yml: |
      server:
        basePath: /kibana

fluent-bit:
  image:
    pullPolicy: IfNotPresent
    tag: 1.5.6
  tolerations:
  - operator: Exists
  serviceMonitor:
    enabled: true
  extraVolumes:
  - configMap:
      defaultMode: 420
      name: fluent-bit-functions
    name: functions
  extraVolumeMounts:
  - mountPath: /fluent-bit/etc/functions.lua
    name: functions
    subPath: functions.lua
  functions: |
    function dedot(tag, timestamp, record)
        if record["kubernetes"] == nil then
            return 0, 0, 0
        end
        dedot_keys(record["kubernetes"]["annotations"])
        dedot_keys(record["kubernetes"]["labels"])
        return 1, timestamp, record
    end

    function dedot_keys(map)
        if map == nil then
            return
        end
        local new_map = {}
        local changed_keys = {}
        for k, v in pairs(map) do
            local deslashed = string.gsub(k, "%/", "_")
            local dedotted = string.gsub(deslashed, "%.", "_")
            if dedotted ~= k then
                new_map[dedotted] = v
                changed_keys[k] = true
            end
        end
        for k in pairs(changed_keys) do
            map[k] = nil
        end
        for k, v in pairs(new_map) do
            map[k] = v
        end
    end
  config:
    service: |
      [SERVICE]
          Flush        5
          Daemon       Off
          Log_Level    info
          Parsers_File parsers.conf
          Parsers_File custom_parsers.conf
          HTTP_Server  On
          HTTP_Listen  0.0.0.0
          HTTP_Port    2020
    inputs: |
      [INPUT]
          Name            tail
          Path            /var/log/containers/*.log
          Parser          docker
          Tag             kube.*
          Mem_Buf_Limit   5MB
          Skip_Long_Lines On
    filters: |
      [FILTER]
          Name                kubernetes
          Match               kube.*
          Merge_Log           On
          Keep_Log            Off
          K8S-Logging.Parser  On
          K8S-Logging.Exclude On
      [FILTER]
          Name    lua
          Match   kube.*
          script  /fluent-bit/etc/functions.lua
          call    dedot
    outputs: |
      [OUTPUT]
          Name            es
          Match           kube.*
          Host            elasticsearch-master
          Logstash_Format On
          Logstash_Prefix logs
          Retry_Limit     False
