elasticsearch:
  antiAffinity: soft
  tolerations:
  - key: playground_test
    operator: Exists
    effect: NoSchedule
  esConfig:
    elasticsearch.yml: |
      xpack:
        monitoring:
          collection:
            enabled: true

kibana:
  httpPort: 5601
  kibanaConfig:
    kibana.yml: |
      server:
        basePath: /kibana

fluent-bit:
  image:
    pullPolicy: IfNotPresent
    tag: 1.5.6
  tolerations:
  - operator: Exists
  serviceMonitor:
    enabled: true
  config:
    service: |
      [SERVICE]
          Flush 5
          Daemon Off
          Log_Level info
          Parsers_File parsers.conf
          Parsers_File custom_parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port 2020
    inputs: |
      [INPUT]
          Name tail
          Path /var/log/containers/*.log
          Parser docker
          Tag kube.*
          Mem_Buf_Limit 5MB
          Skip_Long_Lines On
    filters: |
      [FILTER]
          Name kubernetes
          Match kube.*
          Merge_Log On
          Keep_Log Off
          K8S-Logging.Parser On
          K8S-Logging.Exclude On
    outputs: |
      [OUTPUT]
          Name es
          Match kube.*
          Host elasticsearch-master
          Logstash_Format On
          Retry_Limit False
    customParsers: |
      [PARSER]
          Name docker_no_time
          Format json
          Time_Keep Off
          Time_Key time
          Time_Format %Y-%m-%dT%H:%M:%S.%L
