apiVersion: v1
data:
  {{ (index (index .Values "fluent-bit").extraVolumeMounts 0).subPath }}: |
    {{- (index .Values "fluent-bit").functions | nindent 4 }}
kind: ConfigMap
metadata:
  name: {{ (index (index .Values "fluent-bit").extraVolumes 0).configMap.name }}
