apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-kibana
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /kibana(/|$)(.*)
        backend:
          serviceName: {{ .Release.Name }}-kibana
          servicePort: {{ .Values.kibana.httpPort }}
