apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fluentBitSidecar.appName }}
  namespace: {{ .Values.fluentBitSidecar.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.fluentBitSidecar.appName }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.fluentBitSidecar.appName }}
  ports:
  - name: http
    protocol: TCP
    port: 2020
    targetPort: http
