apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /prometheus(/|$)(.*)
        backend:
          serviceName: prometheus-operator-prometheus
          servicePort: {{ (index .Values "prometheus-operator").prometheus.service.port }}
      - path: /alertmanager(/|$)(.*)
        backend:
          serviceName: prometheus-operator-alertmanager
          servicePort: {{ (index .Values "prometheus-operator").alertmanager.service.port }}
      - path: /grafana(/|$)(.*)
        backend:
          serviceName: prometheus-operator-grafana
          servicePort: {{ (index .Values "prometheus-operator").grafana.service.port }}
