{{- range $entry := .Values.scrape_endpoints -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ $entry.name }}
  labels:
    {{ $entry.label_key }}: {{ $entry.label_value }}
  namespace: {{ $entry.namespace }}
spec:
  selector:
    {{ $entry.label_key }}: {{ $entry.label_value }}
  ports:
  - name: prom-metrics
    port: {{ $entry.port }}
---
{{ end -}}
