apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
data:
  admin.password: {{ .Values.password | b64enc | quote }}
  admin.passwordMtime: {{ (date "2006-01-02T15:04:05Z" .Release.Time) | b64enc | quote }}
{{- range $user := .Values.users }}
  accounts.{{ $user }}.password: {{ $.Values.password | b64enc | quote }}
  accounts.{{ $user }}.passwordMtime: {{ (date "2006-01-02T15:04:05Z" $.Release.Time) | b64enc | quote }}
{{- end }}
type: Opaque
