apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/name: argocd
    app.kubernetes.io/part-of: argocd
  name: argocd
spec:
  endpoints:
  - port: metrics
  namespaceSelector:
    matchNames:
    - argo-cd
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/name: argocd-repo-server
    app.kubernetes.io/part-of: argocd
  name: argocd-repo-server
spec:
  endpoints:
  - port: metrics
  namespaceSelector:
    matchNames:
    - argo-cd
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  name: argocd-server
spec:
  endpoints:
  - port: metrics
  namespaceSelector:
    matchNames:
    - argo-cd
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server-metrics
