apiVersion: v1
data:
  alertmanager.yaml: {{ tpl (.Files.Get "alertmanager/alertmanager.yaml") . | b64enc | quote }}
kind: Secret
metadata:
  name: {{ (index .Values "kube-prometheus-stack").alertmanager.alertmanagerSpec.configSecret }}
type: Opaque
