{{- range $path, $bytes := .Files.Glob "rules/**.yaml" -}}
  {{- $filename := base (trimSuffix ".yaml" $path) | camelcase | lower -}}
  {{- if not (hasSuffix "test" $filename) -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ $filename }}
spec: {{ $.Files.Get $path | nindent 2 }}
---
  {{- end }}
{{ end -}}
